FROM __FROM

ENV JENKINS_HOME /var/jenkins_home
RUN mkdir ${JENKINS_HOME}

COPY ./config/. /config/
RUN chmod +x /config/*
RUN /config/install-dependencies.sh
RUN ln -s ~ /tmp/user_home

ENTRYPOINT ["/config/entrypoint"]
CMD ["/config/start-jenkins-slave.sh"]
