FROM __FROM

ENV WORKSPACE /var/workspace

USER root
RUN mkdir ${WORKSPACE}
COPY ./config/. /config/
RUN chmod +x /config/*
RUN /config/install-dependencies.sh
RUN ln -s ~ /tmp/user_home

ENTRYPOINT ["/config/entrypoint"]
