#!/bin/bash
set -e

if [ $# -ne 2 ]; then
    echo "Usage: $0 <current password> <new password>"
    echo ''
    exit 1
fi


CURRENT_PASSWORD=$1
NEW_PASSWORD=$2

ldappasswd -x -s ${NEW_PASSWORD} -w ${CURRENT_PASSWORD} -D "cn=admin,${LDAP_BASE_DN}" "cn=admin,${LDAP_BASE_DN}"

SSHA_NEW_PASSWORD=`/usr/sbin/slappasswd -h {SSHA} -s ${NEW_PASSWORD}`

cat << "EOF" >/tmp/chpasswd.ldif
dn: olcDatabase={1}hdb,cn=config
changetype: modify
replace: olcRootPW
olcRootPW: ${SSHA_NEW_PASSWORD}
EOF

ldapmodify -H ldapi:// -Y EXTERNAL -f /tmp/chpasswd.ldif
